### ISSUE TITLE
ToDo-List March - 2018

### ISSUE THREAD

**Issue by Kjarrigan** [gosu/gosu#439]
- [x] Fix the CI on master
- [x] Merge Ruby 2.5 support
- [x] Rebase Screenshot PR #431 
- [ ] Merge Screenshot PR #431 
- [ ] Rebase draw_line PR #433 
- [ ] Merge draw_line PR #433
- [ ] Finish and merge Font Refactoring PR #429
- [ ] Release Gosu 0.14
- [ ] Finally rethink and finish Issue #117 

PS: Extracted from #433

**Comment by jlnr** [comment]
I've turned this ticket into a GitHub project: https://github.com/gosu/gosu/projects/2

I thought about using a "milestone" before, but [tickets in a milestone have no logical order](https://github.com/gosu/gosu/milestone/1). Let's try the project thing, I'm curious :)

**Comment by Kjarrigan** [comment]
Oh - never have used the projects before. Sure lets try it :smile:
